### PR TITLE
JavaScript ToDo App

### PR DESCRIPTION
**Pull request by gabrie-lhilarion**
In this  app, I implemented the following features
- Ability to add and delete categories except the default category called "General"
- Functionality to add projects and group them into categories.
- A user can also add ToDo tasks to projects.
- Task can be added or deleted at any time.

### CODE REVIEW

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @gabrie-lhilarion**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] Please make sure to add the required scripts to run the project in development mode. These scripts must be added in the package.js file.
The required scripts are: 
```
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },
```

- [ ] A user should be able to edit any todo. Please make sure to implement this feature.
- [ ] There is a typo in the add todo form, both date fields are name start date. Please make sure to change one of them to due date.
- [ ] You should add the webpack-dev-server dependency to your list of devDependencies. 


---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Comment by gabrie-lhilarion** [comment]
# All required corrections made

- User can edit any todo.
- Date typo removed
- webpack-dev-server added to devDependencies.

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @gabrie-lhilarion**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] In the last review I asked you to make the user capable of editing any todo not just the tasks. That means that the user should be able to edit the name, description, date... etc. Please make sure to add that fuctionality.



---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Comment by gabrie-lhilarion** [comment]
# Required change made
- Added functionality to edit project by double-clicking on a value.

**Review by NtwaliHeritier — APPROVED** [review]
### **STATUS: APPROVED✔✔✔**

Great work making the requested changes👏

You can merge👍👍👍
Happy coding 💻💻💻

**Comment by gabrie-lhilarion** [comment]
## TEST FOR TO-DO LIST
- JEST was used for the testing
- Most of my functions are in Dom.js so 90% of the tests are in Dom.test.js
- More tests can be found in Category.test.js

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Changes Requested, 

Hi @gabrie-lhilarion, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
- [ ] Please add proper tests for all the functions. 
- [ ] Please submit a correct PR becase this PR is already approved. 
- [ ] In Readme add instructions how to test. 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Pull request merged**
